name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        runtime: [win-x64, win-x86, win-arm]  # Add target runtimes here

    runs-on: windows-latest

    env:
      Solution_Name: StockNote.IO.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

    - name: Publish
      run: dotnet publish ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --runtime ${{ matrix.runtime }} --output publish_output_${{ matrix.runtime }}

    - name: Generate self-signed certificate
      run: |
        $cert = New-SelfSignedCertificate -Type CodeSigningCert -Subject "CN=YourCompany" -CertStoreLocation "Cert:\CurrentUser\My"
        $password = ConvertTo-SecureString -String "YourPassword" -Force -AsPlainText
        Export-PfxCertificate -Cert $cert -FilePath "GitHubActionsWorkflow.pfx" -Password $password

    - name: Sign the application
      run: |
        $timestampServer = "http://timestamp.digicert.com"
        $certPath = "GitHubActionsWorkflow.pfx"
        $certPass = "YourPassword"
        $signTool = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe"
        $filesToSign = Get-ChildItem -Path publish_output_${{ matrix.runtime }} -Filter "*.dll,*.exe" -Recurse
        foreach ($file in $filesToSign) {
          & $signTool sign /f $certPath /p $certPass /tr $timestampServer /td sha256 /fd sha256 $file.FullName
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Release Package ${{ matrix.runtime }}
        path: publish_output_${{ matrix.runtime }}
        if-no-files-found: warn
        compression-level: 6
        overwrite: true

    - name: Remove the pfx
      run: Remove-Item -path GitHubActionsWorkflow.pfx

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: Release Package win-x64
        path: ./release_package/win-x64

    - name: Download build artifacts x86
      uses: actions/download-artifact@v4
      with:
        name: Release Package win-x86
        path: ./release_package/win-x86

    - name: Download build artifacts arm
      uses: actions/download-artifact@v4
      with:
        name: Release Package win-arm
        path: ./release_package/win-arm

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v1.0.0  # Update this version as needed
        release_name: Release v1.0.0  # Update this name as needed
        draft: false
        prerelease: false

    - name: Upload Release Asset x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release_package/win-x64
        asset_name: release_package_win-x64.zip
        asset_content_type: application/zip

    - name: Upload Release Asset x86
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release_package/win-x86
        asset_name: release_package_win-x86.zip
        asset_content_type: application/zip

    - name: Upload Release Asset arm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release_package/win-arm
        asset_name: release_package_win-arm.zip
        asset_content_type: application/zip
